
import { ComponentRefactorer } from './ComponentRefactorer';

const proceduralCode = `
import { BaseComponent } from "../../BaseComponent";
export class TestComponent extends BaseComponent {
    async create(props: any): Promise<SceneNode> {
        const root = figma.createText();
        root.name = "Test Text";
        root.characters = "Hello World";
        // Mock setRange calls generated by ComponentGenerator
        await this.setRangeFont(root, 0, 5, {"family":"Inter","style":"Bold"});
        root.setRangeFills(0, 5, [{"type":"SOLID","color":{"r":1,"g":0,"b":0}}]);
        root.setRangeFontSize(0, 5, 24);
        return root;
    }
}
`;

const refactorer = new ComponentRefactorer();
console.log("Running Refactorer on sample code...");
const newCode = refactorer.refactorCode(proceduralCode, "TestComponent");

console.log("--- Refactored Code Output ---");
console.log(newCode);
console.log("------------------------------");

if (newCode.includes("richTextSpans")) {
    console.log("SUCCESS: richTextSpans found!");
} else {
    console.log("FAILURE: richTextSpans NOT found!");
}
